(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for int() with base 10: '|1|24|'"
p3
sS'layer'
p4
S'/home/marco/projects/contabilidad/web2py/applications/sueldos/controllers/vistas.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\ndef reload(target):\n    def js(form):\n        response.js = \'web2py_component("%s","%s")\' % (URL(target),target)\n                \n    return js\n\ndef personal():\n    form = SQLFORM.grid(db.empleados, ui=\'jquery-ui\', user_signature=False)\n    return dict(form=form)\n\ndef escalas():\n\n    nueva=SQLFORM(db.categorias)\n\n    if nueva.process().accepted:\n        response.flash=\'La categoria ha sido agregada\'\n    elif nueva.errors:\n        response.flash=\'El formulario tiene errores\'\n\n    lista=db(db.gremios.id==request.vars.gremio).select()\n    \n    return dict(lista=lista, nueva=nueva)\n\n\ndef importes():\n    \n    nuevo=SQLFORM(db.valores)\n\n    if nuevo.process().accepted:\n        response.flash=\'Aceptado\'\n    elif nuevo.errors:\n        response.flash=\'Errores\'\n\n    lista=db(db.valores.gremio==request.vars.id).select()\n        \n    return dict(listado=lista, nuevo=nuevo)\n\n\n\n\nresponse._vars=response._caller(escalas)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/marco/projects/contabilidad/web2py/gluon/restricted.py", line 212, in restricted\n    exec ccode in environment\n  File "/home/marco/projects/contabilidad/web2py/applications/sueldos/controllers/vistas.py", line 43, in <module>\n  File "/home/marco/projects/contabilidad/web2py/gluon/globals.py", line 193, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/marco/projects/contabilidad/web2py/applications/sueldos/controllers/vistas.py", line 22, in escalas\n    lista=db(db.gremios.id==request.vars.gremio).select()\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 9092, in select\n    return adapter.select(self.query,fields,attributes)\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 2178, in select\n    return super(SQLiteAdapter, self).select(query, fields, attributes)\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 1624, in select\n    sql = self._select(query, fields, attributes)\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 1534, in _select\n    sql_w = \' WHERE \' + self.expand(query) if query else \'\'\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 1313, in expand\n    return op(first, second)\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 1239, in EQ\n    self.expand(second, first.type))\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 1323, in expand\n    return str(self.represent(expression,field_type))\n  File "/home/marco/projects/contabilidad/web2py/gluon/dal.py", line 1753, in represent\n    return str(int(obj))\nValueError: invalid literal for int() with base 10: \'|1|24|\'\n'
p11
s.